[build]	[build]
  base = "frontend"	  base = "frontend" 

[[redirects]]	
  from = "/place/*"	
  to = "https://maps.googleapis.com/maps/api/place/:splat"	
  status = 200	
  force = true	
  headers = {Access-Control-Allow-Origin = "*"} 