[build]
  base = "frontend"

[[redirects]]
  from = "/place/*"
  to = "https://maps.googleapis.com/maps/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = “*”, Authorization = “Bearer AIzaSyD431FCDfbeHQmnEUIsLkPDL-V5noxf2bo”}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"