[build]
  base = "frontend"

[[redirects]]
  from = "/place"
  to = "https://maps.googleapis.com/maps/api"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"